### PR TITLE
Code review of the users module

### PR DESCRIPTION
**Pull request by SeanKuehl**
Do you guys see anything that needs to change?

### CODE REVIEW

**Comment by SeanKuehl** [comment]
I'm using different files for testing and actual because when I run the tests I don't want it to wipe our actual file/file for manual tests

**Comment by SeanKuehl** [comment]
Account information is taken from the file, decrypted, has new information added to it, then is encrypted as a group before being put back on. This means that there is only one encryption key for the file and not one per account(username/password). Also the decrypt function removes the encryption key, so you don't have to worry about removing it from decrypted data.

**Comment by KevinMcDanielConestoga** [comment]
In the MakePrintableCharactersList, incorporate the new line character "\n" as we will want new lines in a note file. In ASCII this would be the 0x0A

**Comment by SeanKuehl** [comment]
> 
> 
> In the MakePrintableCharactersList, incorporate the new line character "\n" as we will want new lines in a note file. In ASCII this would be the 0x0A

I'll make this change and then run the tests to make sure this doesn't cause any problems. If it doesn't cause any problems I'll commit the change.

**Comment by SeanKuehl** [comment]
No kevin, I cannot encrypt a \n character because of the way it works(it generates space and doesn't act like a normal character). I know this because one of the tests failed. If you want to reproduce the problem just add toReturn.push_back('\n'); near the end of MakePrintablesList() and then run the tests and you'll see the one that fails. I would be open to running some manual tests of how we could take inputs from the user(maybe with /n's) and still be able to encrypt them.

**Comment by KevinMcDanielConestoga** [comment]
I ran that scenario, and see what you see. But after some investigation, it is because the is use of the magic number 95. This number is the size of the printable characters, but its not being increased just by adding the one push_back line. 
After removing the magic number that test works. But other tests fail in the PasswordTests, I'm not going to be going down that rabbit hole though.

**Comment by SeanKuehl** [comment]
Could you give me an example message with a /n in it that I'll run? I don't think we need to encrypt this character so long as the rest of the message is encrypted.

**Comment by SeanKuehl** [comment]
> 
> 
> I ran that scenario, and see what you see. But after some investigation, it is because the is use of the magic number 95. This number is the size of the printable characters, but its not being increased just by adding the one push_back line.
> After removing the magic number that test works. But other tests fail in the PasswordTests, I'm not going to be going down that rabbit hole though.

Kevin, I have now a committed a new version that adds \n to what encryption can do and passes all the tests. I did not replace the number with .size() but I did do a #define for the number. I don't know why using the .size() would fail but there were several spots I had to change the 95 so maybe that was why. Try out the latest version of the branch and see if it does what you need.

**Comment by SeanKuehl** [comment]
> 
> 
> > I ran that scenario, and see what you see. But after some investigation, it is because the is use of the magic number 95. This number is the size of the printable characters, but its not being increased just by adding the one push_back line.
> > After removing the magic number that test works. But other tests fail in the PasswordTests, I'm not going to be going down that rabbit hole though.
> 
> Kevin, I have now a committed a new version that adds \n to what encryption can do and passes all the tests. I did not replace the number with .size() but I did do a #define for the number. I don't know why using the .size() would fail but there were several spots I had to change the 95 so maybe that was why. Try out the latest version of the branch and see if it does what you need.

actually, four of the tests do still fail but I looked into them and I know why. These tests are hardcoded. Basically they need to be readjusted for the new printables list. I'll see when I can do this, but for now don't worry about them.

**Comment by SeanKuehl** [comment]
Another update, the failing tests were from password unlock which used the fixed shift of 20, so all the other encrypt/decrypt things worked because the input and output still works, it's only the ones with fixed messages I had to update. Now all the tests work and the \n character has been encorporated. Let me know what you think.

**Comment by KevinMcDanielConestoga** [comment]
Excellent, that's how I would have fixed it, Thanks.

**Pull request merged**
