### PR TITLE
Code Review on the Notes module

### PR DESCRIPTION
**Pull request by KevinMcDanielConestoga**
Review code before integration

### CODE REVIEW

**Comment by SeanKuehl** [comment]
I have a question about "encryptedStrings.push_back("!@#"); //remove this" in note.cpp

**Comment by SeanKuehl** [comment]
Maybe remove the option for notes to be put onto the file without being encrypted. It seems like we shouldn't ask the user for a password or encryption if they're basically the same thing.

**Comment by SeanKuehl** [comment]
Do you always use time to name notes or do you accept a file name from the user?

**Comment by KevinMcDanielConestoga** [comment]
removed the option of encryption, it will always be encrypted. Option of Password still remains.
Modified the GetTitle and added GetPasswordState for ease of use, as requested during code review

**Pull request merged**
