### PR TITLE
Code Review for UI module

### PR DESCRIPTION
**Pull request by Babywise**
Code is not quite complete, but it is almost done.
Code review for the current state of the code.

### CODE REVIEW

**Comment by SeanKuehl** [comment]
I noticed in notemenu.cpp, you do endl twice in the same cout statement. Is this intentional?

**Comment by SeanKuehl** [comment]
I noticed you have a sleep in noteMenu.cpp, is this needed?

**Comment by SeanKuehl** [comment]
Does everything need to inherit from Menu?

**Comment by Babywise** [comment]
double endl is for formating,
sleep is to display errors/success and then return the corresponding menu
yes everything needs to inherit menu because my main is designed to use a loop that will allow function overloading to determine each menu and its options

**Pull request merged**
